apiVersion: v1
kind: ConfigMap
metadata:
  name: rdas-config
  namespace: rdas
data:
  application-prod.yml: |
    rdas:
      soap:
        connect-timeout-ms: 5000
        read-timeout-ms: 10000
      bootstrap:
        refresh-cron: "0 0 2 * * *"