apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rdas-ingress
  namespace: rdas
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: rdas.loopdfs.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rdas
                port:
                  number: 80